version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - redis
  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
