version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  server:
    build: ./server
    container_name: message-server
    ports:
      - "5000:5000"
    depends_on:
      - redis
  client:
    build: ./client
    container_name: message-client
    ports:
      - "8080:80"
    depends_on:
      - server
