version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - server
    networks:
      - app-network


  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=redis:redis:6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
